- name: "Add to Network OS inventory group"
  add_host:
    name: "{{ inventory_hostname }}"
    ansible_network_os: "{{ network_discovery_os | default('unknown') }}"
    groups: "{{ network_discovery_os | default('unknown') }}"
  when: ansible_network_os is not defined

- name: "Print Network OS"
  debug:
    var: ansible_network_os
    verbosity: 2
