- name: "probe eos"
  block:
    - name: "eos: Probe Device"
      no_log: true
      connection: network_cli
      eos_facts:
      vars:
        ansible_network_os: "eos"
    - name: "eos: Define platform"
      set_fact:
        network_discovery_os: "eos"
      when: ansible_net_version is defined
  rescue:
    - debug:
        msg: "not eos!"
  when: network_discovery_os is not defined

- name: "probe ios"
  block:
    - name: "ios: Probe Device"
      no_log: true
      connection: network_cli
      ios_facts:
      vars:
        ansible_network_os: "ios"
    - name: "ios: Define platform"
      set_fact:
        network_discovery_os: "ios"
      when: ansible_net_version is defined
  rescue:
    - debug:
        msg: "not ios!"
  when: network_discovery_os is not defined

- name: "probe iosxr"
  block:
    - name: "iosxr: Probe Device"
      no_log: True
      connection: network_cli
      iosxr_facts:
      vars:
        ansible_network_os: "iosxr"
    - name: "iosxr: Define platform"
      set_fact:
        network_discovery_os: "iosxr"
      when: ansible_net_version is defined
  rescue:
    - debug:
        msg: "not iosxr!"
  when: network_discovery_os is not defined

- name: "probe junos"
  block:
    - name: "junos: Probe Device"
      no_log: True
      connection: netconf
      junos_facts:
      vars:
        ansible_network_os: "junos"
    - name: "junos: Define platform"
      set_fact:
        network_discovery_os: "junos"
      when: ansible_net_version is defined
  rescue:
    - debug:
        msg: "not junos!"
  when: network_discovery_os is not defined

- name: "probe nxos"
  block:
    - name: "nxos: Probe Device"
      no_log: True
      connection: network_cli
      nxos_facts:
      vars:
        ansible_network_os: "nxos"
    - name: "nxos: Define platform"
      set_fact:
        network_discovery_os: "nxos"
      when: ansible_net_version is defined
  rescue:
    - debug:
        msg: "not nxos!"
  when: network_discovery_os is not defined

- name: "probe linux"
  block:
    - name: "linux: Probe Device"
      no_log: True
      connection: ssh
      setup:
    - name: "server: Define platform"
      set_fact:
        network_discovery_os: "linux"
      when: distribution is defined
  rescue:
    - debug:
        msg: "not linux!"
  when: network_discovery_os is not defined
