- name: "ios: test connectivity"
  connection: network_cli
  wait_for_connection:
    timeout: 10

- name: "probe ios"
  block:
    - name: "ios: Probe Device"
      no_log: true
      connection: network_cli
      ios_facts:

    - name: "ios: Define platform"
      set_fact:
        network_discovery_os: "ios"
      when: ansible_net_version is defined

  rescue:
    - debug:
        msg: "not ios!"
